# Generated by Django 3.1.7 on 2021-12-30 20:08

from django.db import migrations, models
import main.utilites


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('address', models.CharField(max_length=126, verbose_name='Адрес')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to=main.utilites.get_timestamp_path, verbose_name='Фото')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
